### these values should be replaced with your own
### put them into the environment before running the main script, using
###      source secrets.sh

export consumerKey=87c...........................
export consumerSecret=c46.......
export token=58a...........................
export tokenSecret=c01.......

